package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"warimas-be/internal/graph/model"
)

// AddCategory is the resolver for the addCategory field.
func (r *mutationResolver) AddCategory(ctx context.Context, name string) (*model.Category, error) {
	c, err := r.CategorySvc.AddCategory(ctx, name)
	if err != nil {
		return nil, err
	}

	return c, nil
}

// AddSubcategory is the resolver for the addSubcategory field.
func (r *mutationResolver) AddSubcategory(ctx context.Context, categoryID string, name string) (*model.Subcategory, error) {
	c, err := r.CategorySvc.AddSubcategory(ctx, categoryID, name)
	if err != nil {
		return nil, err
	}

	return c, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, filter *string, limit *int32, page *int32) ([]*model.Category, error) {
	c, err := r.CategorySvc.GetCategories(ctx, filter, limit, page)
	if err != nil {
		return nil, err
	}

	return c, nil
}

// Subcategory is the resolver for the subcategory field.
func (r *queryResolver) Subcategory(ctx context.Context, filter *string, categoryID string, limit *int32, page *int32) ([]*model.Subcategory, error) {
	s, err := r.CategorySvc.GetSubcategories(ctx, categoryID, filter, limit, page)
	if err != nil {
		return nil, err
	}

	return s, nil
}
