package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"warimas-be/internal/graph/model"
	"warimas-be/internal/order"
	"warimas-be/internal/utils"
)

// CreateOrderFromSession is the resolver for the createOrderFromSession field.
func (r *mutationResolver) CreateOrderFromSession(ctx context.Context, input model.CreateOrderFromSessionInput) (*model.CreateOrderResponse, error) {
	panic(fmt.Errorf("not implemented: CreateOrderFromSession - createOrderFromSession"))
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, input model.UpdateOrderStatusInput) (*model.CreateOrderResponse, error) {
	// Admin only — you already handle auth via @auth(role: ADMIN)
	orderID, err := utils.ToUint(input.OrderID)
	if err != nil {
		return &model.CreateOrderResponse{
			Success: false,
			Message: utils.StrPtr("Invalid order ID"),
		}, nil
	}

	status := order.OrderStatus(input.Status.String())

	err = r.OrderSvc.UpdateOrderStatus(orderID, status)
	if err != nil {
		return &model.CreateOrderResponse{
			Success: false,
			Message: utils.StrPtr(err.Error()),
		}, nil
	}

	return &model.CreateOrderResponse{
		Success: true,
		Message: utils.StrPtr(fmt.Sprintf("Order updated to %s", status)),
	}, nil
}

// CreateSessionCheckout is the resolver for the createSessionCheckout field.
func (r *mutationResolver) CreateSessionCheckout(ctx context.Context, input model.CreateSessionCheckoutInput) (*model.SessionCheckoutResponse, error) {
	panic(fmt.Errorf("not implemented: CreateSessionCheckout - createSessionCheckout"))
}

// UpdateSessionAddress is the resolver for the updateSessionAddress field.
func (r *mutationResolver) UpdateSessionAddress(ctx context.Context, input model.UpdateSessionAddressInput) (*model.UpdateSessionAddressResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateSessionAddress - updateSessionAddress"))
}

// ConfirmCheckoutSession is the resolver for the confirmCheckoutSession field.
func (r *mutationResolver) ConfirmCheckoutSession(ctx context.Context, input model.ConfirmCheckoutSessionInput) (*model.ConfirmCheckoutSessionResponse, error) {
	panic(fmt.Errorf("not implemented: ConfirmCheckoutSession - confirmCheckoutSession"))
}

// OrderList is the resolver for the orderList field.
func (r *queryResolver) OrderList(ctx context.Context, filter *model.OrderFilterInput, sort *model.OrderSortInput, limit *int32, page *int32) (*model.OrderListResponse, error) {
	orders, err := r.OrderSvc.GetOrders(ctx, filter, sort, limit, page)
	if err != nil {
		return nil, err
	}

	return &model.OrderListResponse{
		Items: orders,
		Total: int32(len(orders)),
	}, nil
}

// OrderDetail is the resolver for the orderDetail field.
func (r *queryResolver) OrderDetail(ctx context.Context, orderID string) (*model.Order, error) {
	userID, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	oid, err := utils.ToUint(orderID)
	if err != nil {
		return nil, err
	}

	orderDetail, err := r.OrderSvc.GetOrderDetail(uint(userID), oid, false)
	if err != nil {
		return nil, err
	}

	return order.ToGraphQLOrder(orderDetail), nil
}

// CheckoutSession is the resolver for the checkoutSession field.
func (r *queryResolver) CheckoutSession(ctx context.Context, id string) (*model.CheckoutSession, error) {
	panic(fmt.Errorf("not implemented: CheckoutSession - checkoutSession"))
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateOrder(ctx context.Context) (*model.CreateOrderResponse, error) {
	userID, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return &model.CreateOrderResponse{
			Success: false,
			Message: utils.StrPtr("Unauthorized"),
		}, nil
	}

	userEmail := utils.GetUserEmailFromContext(ctx)

	newOrder, payment, err := r.OrderSvc.CreateOrder(uint(userID), userEmail)
	if err != nil {
		return &model.CreateOrderResponse{
			Success: false,
			Message: utils.StrPtr(err.Error()),
		}, nil
	}

	return &model.CreateOrderResponse{
		Success:     true,
		Message:     utils.StrPtr("Order created successfully"),
		Order:       order.ToGraphQLOrder(newOrder),
		PaymentURL:  payment.InvoiceURL,
		PaymentStat: payment.Status,
	}, nil
}
func (r *mutationResolver) CreateSessionOrder(ctx context.Context, input model.CreateSessionOrderInput) (*model.SessionOrderResponse, error) {
	panic(fmt.Errorf("not implemented: CreateSessionOrder - createSessionOrder"))
}
*/
