package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"warimas-be/internal/graph/model"
)

// PackageRecomamendation is the resolver for the packageRecomamendation field.
func (r *queryResolver) PackageRecomamendation(ctx context.Context, filter *model.PackageFilterInput, sort *model.PackageSortInput, limit *int32, page *int32) (*model.PackageResponse, error) {
	panic(fmt.Errorf("not implemented: PackageRecomamendation - packageRecomamendation"))
}
