package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"warimas-be/internal/graph/model"
	"warimas-be/internal/logger"
	prodInternal "warimas-be/internal/product"
	"warimas-be/internal/utils"

	"go.uber.org/zap"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	_, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized: please login first")
	}

	p, err := r.ProductSvc.Create(ctx, input)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:   fmt.Sprint(p.ID),
		Name: p.Name,
	}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProduct) (*model.Product, error) {
	_, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized: please login first")
	}

	p, err := r.ProductSvc.Update(ctx, input)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:   fmt.Sprint(p.ID),
		Name: p.Name,
	}, nil
}

// ProductList is the resolver for the productList field.
func (r *queryResolver) ProductList(ctx context.Context, filter *model.ProductFilterInput, sort *model.ProductSortInput, page *int32, limit *int32) (*model.ProductPage, error) {
	log := logger.FromCtx(ctx).With(
		zap.String("layer", "resolver"),
		zap.String("method", "ProductList"),
	)

	// 1. Input Normalization & Defaults
	p := int32(1)
	if page != nil && *page > 0 {
		p = *page
	}

	l := int32(20)
	if limit != nil && *limit > 0 {
		l = *limit
	}
	// Cap limit to prevent abuse
	if l > 100 {
		l = 100
	}

	log.Info("resolver started",
		zap.Int32("page", p),
		zap.Int32("limit", l),
	)

	// 2. Optimization: Check requested fields to avoid unnecessary count query
	includeCount := utils.HasAnyField(ctx,
		"totalCount",
		"totalPages",
		"hasNext",
	)

	var sortField *model.ProductSortField
	var sortDirection *model.SortDirection

	if sort != nil {
		sortField = &sort.Field
		sortDirection = &sort.Direction
	}

	if filter == nil {
		filter = &model.ProductFilterInput{}
	}

	opts := prodInternal.ProductQueryOptions{
		CategoryID:   filter.CategoryID,
		CategorySlug: filter.CategorySlug,
		SellerName:   filter.SellerName,
		Status:       filter.Status,
		Search:       filter.Search,
		MinPrice:     filter.MinPrice,
		MaxPrice:     filter.MaxPrice,
		InStock:      filter.InStock,

		SortField:     prodInternal.MapSortField(sortField),
		SortDirection: prodInternal.MapSortDirection(sortDirection),

		Page:         p,
		Limit:        l,
		IncludeCount: includeCount,
	}

	// 4. Call Service
	result, err := r.ProductSvc.GetList(ctx, opts)
	if err != nil {
		log.Error("failed to fetch product list", zap.Error(err))
		return nil, err
	}

	// map domain → graphql
	items := make([]*model.Product, 0, len(result.Items))
	for _, p := range result.Items {
		items = append(items, prodInternal.MapProductToGraphQL(p))
	}

	var totalCount int32 = 0
	var totalPages int32 = 0
	var hasNext bool = false

	if includeCount && result.TotalCount != nil {
		totalCount = int32(*result.TotalCount)
		if l > 0 {
			totalPages = (totalCount + l - 1) / l
		}
		hasNext = p < totalPages
	}

	log.Info("resolver success",
		zap.Int("items_count", len(items)),
		zap.Int32("total_count", totalCount),
	)

	return &model.ProductPage{
		Items:      items,
		Page:       p,
		Limit:      l,
		TotalCount: totalCount,
		TotalPages: totalPages,
		HasNext:    hasNext,
	}, nil
}

// ProductsHome is the resolver for the productsHome field.
func (r *queryResolver) ProductsHome(ctx context.Context, filter *model.ProductFilterInput, sort *model.ProductSortInput, page *int32, limit *int32) ([]*model.ProductByCategory, error) {
	log := logger.FromCtx(ctx)
	log.Info("ProductsHome resolver called")

	// -------------------------------
	// 1. Normalize inputs
	// -------------------------------
	if filter == nil {
		filter = &model.ProductFilterInput{}
	}

	// Pagination defaults
	var (
		defaultPage  int32 = 1
		defaultLimit int32 = 20
		maxLimit     int32 = 50
	)

	p := defaultPage
	l := defaultLimit

	if page != nil && *page > 0 {
		p = *page
	}
	if limit != nil && *limit > 0 {
		l = *limit
	}
	if l > maxLimit {
		l = maxLimit
	}

	// -------------------------------
	// 2. Sorting normalization
	// -------------------------------
	var sortField *model.ProductSortField
	var sortDirection *model.SortDirection

	if sort != nil {
		sortField = &sort.Field
		sortDirection = &sort.Direction
	}

	// -------------------------------
	// 3. Build service query options
	// -------------------------------
	opts := prodInternal.ProductQueryOptions{
		CategoryID:   filter.CategoryID,
		CategorySlug: filter.CategorySlug,
		SellerName:   filter.SellerName,
		Status:       filter.Status,
		Search:       filter.Search,
		MinPrice:     filter.MinPrice,
		MaxPrice:     filter.MaxPrice,
		InStock:      filter.InStock,

		SortField:     prodInternal.MapSortField(sortField),
		SortDirection: prodInternal.MapSortDirection(sortDirection),

		Page:  p,
		Limit: l,
	}

	log.Info("Fetching products by group",
		zap.Int32("page", p),
		zap.Int32("limit", l),
		zap.Any("filter", filter),
	)

	// -------------------------------
	// 4. Fetch data from service
	// -------------------------------
	grouped, err := r.ProductSvc.GetProductsByGroup(ctx, opts)
	if err != nil {
		log.Error("GetProductsByGroup failed", zap.Error(err))
		return nil, err
	}

	log.Info("Products fetched successfully",
		zap.Int("group_count", len(grouped)),
	)

	// -------------------------------
	// 5. Convert to GraphQL response
	// -------------------------------
	result := make([]*model.ProductByCategory, 0, len(grouped))

	for _, g := range grouped {
		// Skip empty categories (optional, business decision)
		if g.TotalProducts == 0 {
			continue
		}

		result = append(result, prodInternal.MapProductByCategoryToGraphQL(g))
	}

	log.Info("ProductsHome resolver completed",
		zap.Int("returned_groups", len(result)),
	)

	return result, nil
}

// ProductDetail is the resolver for the productDetail field.
func (r *queryResolver) ProductDetail(ctx context.Context, productID string) (*model.Product, error) {
	log := logger.FromCtx(ctx).With(
		zap.String("resolver", "ProductDetail"),
		zap.String("product_id", productID),
	)

	log.Debug("resolver called")
	product, err := r.ProductSvc.GetProductByID(ctx, productID)

	if errors.Is(err, prodInternal.ErrProductNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	productGraph := prodInternal.MapProductToGraphQL(product)

	log.Debug("product found")
	return productGraph, nil
}
