package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"
	"warimas-be/internal/graph/model"
	"warimas-be/internal/product"
	"warimas-be/internal/utils"
)

func mapSortField(f *model.ProductSortField) product.ProductSortField {
	if f == nil {
		return product.ProductSortFieldCreatedAt
	}

	switch *f {
	case model.ProductSortFieldPrice:
		return product.ProductSortFieldPrice
	case model.ProductSortFieldName:
		return product.ProductSortFieldName
	default:
		return product.ProductSortFieldCreatedAt
	}
}

func mapSortDirection(d *model.SortDirection) product.SortDirection {
	if d == nil {
		return product.SortDirectionDesc
	}

	if *d == model.SortDirectionAsc {
		return product.SortDirectionAsc
	}
	return product.SortDirectionDesc
}

func mapProductToGraphQL(p *product.Product) *model.Product {
	status := p.Status

	return &model.Product{
		ID:              p.ID,
		Name:            p.Name,
		SellerID:        p.SellerID,
		SellerName:      p.SellerName,
		CategoryID:      p.CategoryID,
		CategoryName:    p.CategoryName,
		SubcategoryID:   p.SubcategoryID,
		SubcategoryName: p.SubcategoryName,
		Slug:            p.Slug,
		ImageURL:        p.ImageURL,
		Description:     p.Description,
		Status:          &status,
		CreatedAt:       p.CreatedAt.Format(time.RFC3339),
		UpdatedAt:       formatTimePtr(p.UpdatedAt),
	}
}

func formatTimePtr(t *time.Time) *string {
	if t == nil {
		return nil
	}
	s := t.Format(time.RFC3339)
	return &s
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	_, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized: please login first")
	}

	p, err := r.ProductSvc.Create(ctx, input)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:   fmt.Sprint(p.ID),
		Name: p.Name,
	}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProduct) (*model.Product, error) {
	_, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized: please login first")
	}

	p, err := r.ProductSvc.Update(ctx, input)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:   fmt.Sprint(p.ID),
		Name: p.Name,
	}, nil
}

// ProductList is the resolver for the productList field.
func (r *queryResolver) ProductList(
	ctx context.Context,
	filter *model.ProductFilterInput,
	sort *model.ProductSortInput,
	page *int32, limit *int32) (*model.ProductPage, error) {

	p := int32(1)
	l := int32(20)

	if page != nil && *page > 0 {
		p = *page
	}
	if limit != nil && *limit > 0 {
		l = *limit
	}
	includeCount := false

	if utils.HasAnyField(ctx,
		"totalCount",
		"totalPages",
		"hasNext",
	) {
		includeCount = true
	}

	var sortField *model.ProductSortField
	var sortDirection *model.SortDirection

	if sort != nil {
		sortField = &sort.Field
		sortDirection = &sort.Direction
	}

	if filter == nil {
		filter = &model.ProductFilterInput{}
	}

	opts := product.ProductQueryOptions{
		CategoryID: filter.CategoryID,
		SellerName: filter.SellerName,
		Status:     filter.Status,
		Search:     filter.Search,
		MinPrice:   filter.MinPrice,
		MaxPrice:   filter.MaxPrice,
		InStock:    filter.InStock,

		SortField:     mapSortField(sortField),
		SortDirection: mapSortDirection(sortDirection),

		Page:  p,
		Limit: l,

		IncludeCount: includeCount,
	}

	// 2. Fetch grouped products
	// call service
	result, err := r.ProductSvc.GetList(ctx, opts)
	if err != nil {
		return nil, err
	}

	// map domain → graphql
	items := make([]*model.Product, 0, len(result.Items))
	for _, p := range result.Items {
		items = append(items, mapProductToGraphQL(p))
	}

	var totalCount int32 = 0
	var totalPages int32 = 0
	var hasNext bool = false

	if includeCount && result.TotalCount != nil {
		totalCount = int32(*result.TotalCount)
		totalPages = (totalCount + l - 1) / l
		hasNext = p < totalPages
	}

	return &model.ProductPage{
		Items:      items,
		Page:       p,
		Limit:      l,
		TotalCount: totalCount,
		TotalPages: totalPages,
		HasNext:    hasNext,
	}, nil

}

// Products is the resolver for the products field.
func (r *queryResolver) ProductsHome(ctx context.Context, filter *model.ProductFilterInput, sort *model.ProductSortInput, limit *int32, page *int32) ([]*model.ProductByCategory, error) {

	p := int32(1)
	l := int32(20)

	if page != nil && *page > 0 {
		p = *page
	}
	if limit != nil && *limit > 0 {
		l = *limit
	}

	var sortField *model.ProductSortField
	var sortDirection *model.SortDirection

	if sort != nil {
		sortField = &sort.Field
		sortDirection = &sort.Direction
	}

	opts := product.ProductQueryOptions{
		CategoryID: filter.CategoryID,
		SellerName: filter.SellerName,
		Status:     filter.Status,
		Search:     filter.Search,
		MinPrice:   filter.MinPrice,
		MaxPrice:   filter.MaxPrice,
		InStock:    filter.InStock,

		SortField:     mapSortField(sortField),
		SortDirection: mapSortDirection(sortDirection),

		Page:  p,
		Limit: l,
	}

	// 2. Fetch grouped products
	grouped, err := r.ProductSvc.GetProductsByGroup(ctx, opts)
	if err != nil {
		return nil, err
	}

	// 3. Convert service output -> GraphQL response
	result := make([]*model.ProductByCategory, 0, len(grouped))

	for _, g := range grouped {
		if len(g.Products) == 0 {
			continue // skip empty categories
		}

		result = append(result, &model.ProductByCategory{
			CategoryName:  g.CategoryName,
			TotalProducts: g.TotalProducts,
			Products:      g.Products,
		})
	}

	return result, nil
}

// ProductDetail is the resolver for the productDetail field.
func (r *queryResolver) ProductDetail(ctx context.Context, productID string) (*model.Product, error) {
	product, err := r.ProductSvc.GetProductByID(ctx, productID)
	if err == sql.ErrNoRows {
		return nil, nil // ✅ allowed
	}
	if err != nil {
		return nil, err
	}

	return product, nil
}
