// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"context"
	"embed"
	"errors"
	"fmt"
	"sync/atomic"
	"warimas-be/internal/graph/model"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type DirectiveRoot struct {
	Auth func(ctx context.Context, obj any, next graphql.Resolver, role *model.Role) (res any, err error)
}

type ComplexityRoot struct {
	AddToCartResponse struct {
		CartItem func(childComplexity int) int
		Message  func(childComplexity int) int
		Success  func(childComplexity int) int
	}

	AuthResponse struct {
		Token func(childComplexity int) int
		User  func(childComplexity int) int
	}

	CartItem struct {
		CreatedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		Product   func(childComplexity int) int
		Quantity  func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
		UserID    func(childComplexity int) int
	}

	Category struct {
		ID   func(childComplexity int) int
		Name func(childComplexity int) int
	}

	CreateOrderResponse struct {
		Message     func(childComplexity int) int
		Order       func(childComplexity int) int
		PaymentStat func(childComplexity int) int
		PaymentURL  func(childComplexity int) int
		Success     func(childComplexity int) int
	}

	Mutation struct {
		AddCategory       func(childComplexity int, name string) int
		AddSubcategory    func(childComplexity int, categoryID string, name string) int
		AddToCart         func(childComplexity int, input model.AddToCartInput) int
		CreateOrder       func(childComplexity int) int
		CreateProduct     func(childComplexity int, input model.NewProduct) int
		CreateVariants    func(childComplexity int, input []*model.NewVariant) int
		Login             func(childComplexity int, input model.LoginInput) int
		Register          func(childComplexity int, input model.RegisterInput) int
		RemoveFromCart    func(childComplexity int, variantID string) int
		UpdateCart        func(childComplexity int, input model.UpdateCartInput) int
		UpdateOrderStatus func(childComplexity int, input model.UpdateOrderStatusInput) int
		UpdateProduct     func(childComplexity int, input model.UpdateProduct) int
		UpdateVariants    func(childComplexity int, input []*model.UpdateVariant) int
	}

	MyCartResponse struct {
		Data    func(childComplexity int) int
		Message func(childComplexity int) int
		Success func(childComplexity int) int
	}

	Order struct {
		CreatedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		Items     func(childComplexity int) int
		Status    func(childComplexity int) int
		Total     func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
		UserID    func(childComplexity int) int
	}

	OrderItem struct {
		ID       func(childComplexity int) int
		OrderID  func(childComplexity int) int
		Price    func(childComplexity int) int
		Product  func(childComplexity int) int
		Quantity func(childComplexity int) int
	}

	Package struct {
		ID       func(childComplexity int) int
		ImageURL func(childComplexity int) int
		Items    func(childComplexity int) int
		Name     func(childComplexity int) int
		UserID   func(childComplexity int) int
	}

	PackageItem struct {
		CreatedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		ImageURL  func(childComplexity int) int
		Name      func(childComplexity int) int
		PackageID func(childComplexity int) int
		Price     func(childComplexity int) int
		Quantity  func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
		VariantID func(childComplexity int) int
	}

	PackageResponse struct {
		Data    func(childComplexity int) int
		Message func(childComplexity int) int
		Success func(childComplexity int) int
	}

	PageInfo struct {
		EndCursor       func(childComplexity int) int
		HasNextPage     func(childComplexity int) int
		HasPreviousPage func(childComplexity int) int
		StartCursor     func(childComplexity int) int
	}

	Product struct {
		CategoryID      func(childComplexity int) int
		CategoryName    func(childComplexity int) int
		CreatedAt       func(childComplexity int) int
		Description     func(childComplexity int) int
		ID              func(childComplexity int) int
		ImageURL        func(childComplexity int) int
		Name            func(childComplexity int) int
		SellerID        func(childComplexity int) int
		SellerName      func(childComplexity int) int
		Slug            func(childComplexity int) int
		Status          func(childComplexity int) int
		SubcategoryID   func(childComplexity int) int
		SubcategoryName func(childComplexity int) int
		UpdatedAt       func(childComplexity int) int
		Variants        func(childComplexity int) int
	}

	ProductByCategory struct {
		CategoryName  func(childComplexity int) int
		Products      func(childComplexity int) int
		TotalProducts func(childComplexity int) int
	}

	ProductCart struct {
		CategoryID      func(childComplexity int) int
		CategoryName    func(childComplexity int) int
		CreatedAt       func(childComplexity int) int
		Description     func(childComplexity int) int
		ID              func(childComplexity int) int
		ImageURL        func(childComplexity int) int
		Name            func(childComplexity int) int
		SellerID        func(childComplexity int) int
		SellerName      func(childComplexity int) int
		Slug            func(childComplexity int) int
		Status          func(childComplexity int) int
		SubcategoryID   func(childComplexity int) int
		SubcategoryName func(childComplexity int) int
		UpdatedAt       func(childComplexity int) int
		Variant         func(childComplexity int) int
	}

	ProductConnection struct {
		Edges      func(childComplexity int) int
		PageInfo   func(childComplexity int) int
		TotalCount func(childComplexity int) int
	}

	ProductEdge struct {
		Cursor func(childComplexity int) int
		Node   func(childComplexity int) int
	}

	ProductPage struct {
		HasNext    func(childComplexity int) int
		Items      func(childComplexity int) int
		Limit      func(childComplexity int) int
		Page       func(childComplexity int) int
		TotalCount func(childComplexity int) int
		TotalPages func(childComplexity int) int
	}

	Query struct {
		Category               func(childComplexity int, filter *string, limit *int32, page *int32) int
		MyCart                 func(childComplexity int, filter *model.CartFilterInput, sort *model.CartSortInput, limit *int32, page *int32) int
		OrderDetail            func(childComplexity int, orderID string) int
		OrderList              func(childComplexity int, filter *model.OrderFilterInput, sort *model.OrderSortInput, limit *int32, page *int32) int
		PackageRecomamendation func(childComplexity int, filter *model.PackageFilterInput, sort *model.PackageSortInput, limit *int32, page *int32) int
		ProductDetail          func(childComplexity int, productID string) int
		ProductList            func(childComplexity int, filter *model.ProductFilterInput, sort *model.ProductSortInput, page *int32, limit *int32) int
		ProductsHome           func(childComplexity int, filter *model.ProductFilterInput, sort *model.ProductSortInput, limit *int32, page *int32) int
		Subcategory            func(childComplexity int, filter *string, categoryID string, limit *int32, page *int32) int
	}

	Response struct {
		Message func(childComplexity int) int
		Success func(childComplexity int) int
	}

	Subcategory struct {
		CategoryID func(childComplexity int) int
		ID         func(childComplexity int) int
		Name       func(childComplexity int) int
	}

	User struct {
		Email func(childComplexity int) int
		ID    func(childComplexity int) int
		Role  func(childComplexity int) int
	}

	Variant struct {
		CategoryID   func(childComplexity int) int
		CreatedAt    func(childComplexity int) int
		Description  func(childComplexity int) int
		ID           func(childComplexity int) int
		ImageURL     func(childComplexity int) int
		Name         func(childComplexity int) int
		Price        func(childComplexity int) int
		ProductID    func(childComplexity int) int
		QuantityType func(childComplexity int) int
		SellerID     func(childComplexity int) int
		Stock        func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "AddToCartResponse.cartItem":
		if e.complexity.AddToCartResponse.CartItem == nil {
			break
		}

		return e.complexity.AddToCartResponse.CartItem(childComplexity), true

	case "AddToCartResponse.message":
		if e.complexity.AddToCartResponse.Message == nil {
			break
		}

		return e.complexity.AddToCartResponse.Message(childComplexity), true

	case "AddToCartResponse.success":
		if e.complexity.AddToCartResponse.Success == nil {
			break
		}

		return e.complexity.AddToCartResponse.Success(childComplexity), true

	case "AuthResponse.token":
		if e.complexity.AuthResponse.Token == nil {
			break
		}

		return e.complexity.AuthResponse.Token(childComplexity), true

	case "AuthResponse.user":
		if e.complexity.AuthResponse.User == nil {
			break
		}

		return e.complexity.AuthResponse.User(childComplexity), true

	case "CartItem.createdAt":
		if e.complexity.CartItem.CreatedAt == nil {
			break
		}

		return e.complexity.CartItem.CreatedAt(childComplexity), true

	case "CartItem.id":
		if e.complexity.CartItem.ID == nil {
			break
		}

		return e.complexity.CartItem.ID(childComplexity), true

	case "CartItem.product":
		if e.complexity.CartItem.Product == nil {
			break
		}

		return e.complexity.CartItem.Product(childComplexity), true

	case "CartItem.quantity":
		if e.complexity.CartItem.Quantity == nil {
			break
		}

		return e.complexity.CartItem.Quantity(childComplexity), true

	case "CartItem.updatedAt":
		if e.complexity.CartItem.UpdatedAt == nil {
			break
		}

		return e.complexity.CartItem.UpdatedAt(childComplexity), true

	case "CartItem.userId":
		if e.complexity.CartItem.UserID == nil {
			break
		}

		return e.complexity.CartItem.UserID(childComplexity), true

	case "Category.id":
		if e.complexity.Category.ID == nil {
			break
		}

		return e.complexity.Category.ID(childComplexity), true

	case "Category.name":
		if e.complexity.Category.Name == nil {
			break
		}

		return e.complexity.Category.Name(childComplexity), true

	case "CreateOrderResponse.message":
		if e.complexity.CreateOrderResponse.Message == nil {
			break
		}

		return e.complexity.CreateOrderResponse.Message(childComplexity), true

	case "CreateOrderResponse.order":
		if e.complexity.CreateOrderResponse.Order == nil {
			break
		}

		return e.complexity.CreateOrderResponse.Order(childComplexity), true

	case "CreateOrderResponse.paymentStat":
		if e.complexity.CreateOrderResponse.PaymentStat == nil {
			break
		}

		return e.complexity.CreateOrderResponse.PaymentStat(childComplexity), true

	case "CreateOrderResponse.paymentURL":
		if e.complexity.CreateOrderResponse.PaymentURL == nil {
			break
		}

		return e.complexity.CreateOrderResponse.PaymentURL(childComplexity), true

	case "CreateOrderResponse.success":
		if e.complexity.CreateOrderResponse.Success == nil {
			break
		}

		return e.complexity.CreateOrderResponse.Success(childComplexity), true

	case "Mutation.addCategory":
		if e.complexity.Mutation.AddCategory == nil {
			break
		}

		args, err := ec.field_Mutation_addCategory_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.AddCategory(childComplexity, args["name"].(string)), true

	case "Mutation.addSubcategory":
		if e.complexity.Mutation.AddSubcategory == nil {
			break
		}

		args, err := ec.field_Mutation_addSubcategory_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.AddSubcategory(childComplexity, args["categoryID"].(string), args["name"].(string)), true

	case "Mutation.addToCart":
		if e.complexity.Mutation.AddToCart == nil {
			break
		}

		args, err := ec.field_Mutation_addToCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.AddToCart(childComplexity, args["input"].(model.AddToCartInput)), true

	case "Mutation.createOrder":
		if e.complexity.Mutation.CreateOrder == nil {
			break
		}

		return e.complexity.Mutation.CreateOrder(childComplexity), true

	case "Mutation.createProduct":
		if e.complexity.Mutation.CreateProduct == nil {
			break
		}

		args, err := ec.field_Mutation_createProduct_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateProduct(childComplexity, args["input"].(model.NewProduct)), true

	case "Mutation.createVariants":
		if e.complexity.Mutation.CreateVariants == nil {
			break
		}

		args, err := ec.field_Mutation_createVariants_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateVariants(childComplexity, args["input"].([]*model.NewVariant)), true

	case "Mutation.login":
		if e.complexity.Mutation.Login == nil {
			break
		}

		args, err := ec.field_Mutation_login_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.Login(childComplexity, args["input"].(model.LoginInput)), true

	case "Mutation.register":
		if e.complexity.Mutation.Register == nil {
			break
		}

		args, err := ec.field_Mutation_register_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.Register(childComplexity, args["input"].(model.RegisterInput)), true

	case "Mutation.removeFromCart":
		if e.complexity.Mutation.RemoveFromCart == nil {
			break
		}

		args, err := ec.field_Mutation_removeFromCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.RemoveFromCart(childComplexity, args["variantId"].(string)), true

	case "Mutation.updateCart":
		if e.complexity.Mutation.UpdateCart == nil {
			break
		}

		args, err := ec.field_Mutation_updateCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateCart(childComplexity, args["input"].(model.UpdateCartInput)), true

	case "Mutation.updateOrderStatus":
		if e.complexity.Mutation.UpdateOrderStatus == nil {
			break
		}

		args, err := ec.field_Mutation_updateOrderStatus_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateOrderStatus(childComplexity, args["input"].(model.UpdateOrderStatusInput)), true

	case "Mutation.updateProduct":
		if e.complexity.Mutation.UpdateProduct == nil {
			break
		}

		args, err := ec.field_Mutation_updateProduct_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateProduct(childComplexity, args["input"].(model.UpdateProduct)), true

	case "Mutation.updateVariants":
		if e.complexity.Mutation.UpdateVariants == nil {
			break
		}

		args, err := ec.field_Mutation_updateVariants_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateVariants(childComplexity, args["input"].([]*model.UpdateVariant)), true

	case "MyCartResponse.data":
		if e.complexity.MyCartResponse.Data == nil {
			break
		}

		return e.complexity.MyCartResponse.Data(childComplexity), true

	case "MyCartResponse.message":
		if e.complexity.MyCartResponse.Message == nil {
			break
		}

		return e.complexity.MyCartResponse.Message(childComplexity), true

	case "MyCartResponse.success":
		if e.complexity.MyCartResponse.Success == nil {
			break
		}

		return e.complexity.MyCartResponse.Success(childComplexity), true

	case "Order.createdAt":
		if e.complexity.Order.CreatedAt == nil {
			break
		}

		return e.complexity.Order.CreatedAt(childComplexity), true

	case "Order.id":
		if e.complexity.Order.ID == nil {
			break
		}

		return e.complexity.Order.ID(childComplexity), true

	case "Order.items":
		if e.complexity.Order.Items == nil {
			break
		}

		return e.complexity.Order.Items(childComplexity), true

	case "Order.status":
		if e.complexity.Order.Status == nil {
			break
		}

		return e.complexity.Order.Status(childComplexity), true

	case "Order.total":
		if e.complexity.Order.Total == nil {
			break
		}

		return e.complexity.Order.Total(childComplexity), true

	case "Order.updatedAt":
		if e.complexity.Order.UpdatedAt == nil {
			break
		}

		return e.complexity.Order.UpdatedAt(childComplexity), true

	case "Order.userId":
		if e.complexity.Order.UserID == nil {
			break
		}

		return e.complexity.Order.UserID(childComplexity), true

	case "OrderItem.id":
		if e.complexity.OrderItem.ID == nil {
			break
		}

		return e.complexity.OrderItem.ID(childComplexity), true

	case "OrderItem.orderId":
		if e.complexity.OrderItem.OrderID == nil {
			break
		}

		return e.complexity.OrderItem.OrderID(childComplexity), true

	case "OrderItem.price":
		if e.complexity.OrderItem.Price == nil {
			break
		}

		return e.complexity.OrderItem.Price(childComplexity), true

	case "OrderItem.product":
		if e.complexity.OrderItem.Product == nil {
			break
		}

		return e.complexity.OrderItem.Product(childComplexity), true

	case "OrderItem.quantity":
		if e.complexity.OrderItem.Quantity == nil {
			break
		}

		return e.complexity.OrderItem.Quantity(childComplexity), true

	case "Package.id":
		if e.complexity.Package.ID == nil {
			break
		}

		return e.complexity.Package.ID(childComplexity), true

	case "Package.imageUrl":
		if e.complexity.Package.ImageURL == nil {
			break
		}

		return e.complexity.Package.ImageURL(childComplexity), true

	case "Package.items":
		if e.complexity.Package.Items == nil {
			break
		}

		return e.complexity.Package.Items(childComplexity), true

	case "Package.name":
		if e.complexity.Package.Name == nil {
			break
		}

		return e.complexity.Package.Name(childComplexity), true

	case "Package.userId":
		if e.complexity.Package.UserID == nil {
			break
		}

		return e.complexity.Package.UserID(childComplexity), true

	case "PackageItem.createdAt":
		if e.complexity.PackageItem.CreatedAt == nil {
			break
		}

		return e.complexity.PackageItem.CreatedAt(childComplexity), true

	case "PackageItem.id":
		if e.complexity.PackageItem.ID == nil {
			break
		}

		return e.complexity.PackageItem.ID(childComplexity), true

	case "PackageItem.imageUrl":
		if e.complexity.PackageItem.ImageURL == nil {
			break
		}

		return e.complexity.PackageItem.ImageURL(childComplexity), true

	case "PackageItem.name":
		if e.complexity.PackageItem.Name == nil {
			break
		}

		return e.complexity.PackageItem.Name(childComplexity), true

	case "PackageItem.packageId":
		if e.complexity.PackageItem.PackageID == nil {
			break
		}

		return e.complexity.PackageItem.PackageID(childComplexity), true

	case "PackageItem.price":
		if e.complexity.PackageItem.Price == nil {
			break
		}

		return e.complexity.PackageItem.Price(childComplexity), true

	case "PackageItem.quantity":
		if e.complexity.PackageItem.Quantity == nil {
			break
		}

		return e.complexity.PackageItem.Quantity(childComplexity), true

	case "PackageItem.updatedAt":
		if e.complexity.PackageItem.UpdatedAt == nil {
			break
		}

		return e.complexity.PackageItem.UpdatedAt(childComplexity), true

	case "PackageItem.variantId":
		if e.complexity.PackageItem.VariantID == nil {
			break
		}

		return e.complexity.PackageItem.VariantID(childComplexity), true

	case "PackageResponse.data":
		if e.complexity.PackageResponse.Data == nil {
			break
		}

		return e.complexity.PackageResponse.Data(childComplexity), true

	case "PackageResponse.message":
		if e.complexity.PackageResponse.Message == nil {
			break
		}

		return e.complexity.PackageResponse.Message(childComplexity), true

	case "PackageResponse.success":
		if e.complexity.PackageResponse.Success == nil {
			break
		}

		return e.complexity.PackageResponse.Success(childComplexity), true

	case "PageInfo.endCursor":
		if e.complexity.PageInfo.EndCursor == nil {
			break
		}

		return e.complexity.PageInfo.EndCursor(childComplexity), true

	case "PageInfo.hasNextPage":
		if e.complexity.PageInfo.HasNextPage == nil {
			break
		}

		return e.complexity.PageInfo.HasNextPage(childComplexity), true

	case "PageInfo.hasPreviousPage":
		if e.complexity.PageInfo.HasPreviousPage == nil {
			break
		}

		return e.complexity.PageInfo.HasPreviousPage(childComplexity), true

	case "PageInfo.startCursor":
		if e.complexity.PageInfo.StartCursor == nil {
			break
		}

		return e.complexity.PageInfo.StartCursor(childComplexity), true

	case "Product.categoryID":
		if e.complexity.Product.CategoryID == nil {
			break
		}

		return e.complexity.Product.CategoryID(childComplexity), true

	case "Product.categoryName":
		if e.complexity.Product.CategoryName == nil {
			break
		}

		return e.complexity.Product.CategoryName(childComplexity), true

	case "Product.createdAt":
		if e.complexity.Product.CreatedAt == nil {
			break
		}

		return e.complexity.Product.CreatedAt(childComplexity), true

	case "Product.description":
		if e.complexity.Product.Description == nil {
			break
		}

		return e.complexity.Product.Description(childComplexity), true

	case "Product.id":
		if e.complexity.Product.ID == nil {
			break
		}

		return e.complexity.Product.ID(childComplexity), true

	case "Product.imageUrl":
		if e.complexity.Product.ImageURL == nil {
			break
		}

		return e.complexity.Product.ImageURL(childComplexity), true

	case "Product.name":
		if e.complexity.Product.Name == nil {
			break
		}

		return e.complexity.Product.Name(childComplexity), true

	case "Product.sellerId":
		if e.complexity.Product.SellerID == nil {
			break
		}

		return e.complexity.Product.SellerID(childComplexity), true

	case "Product.sellerName":
		if e.complexity.Product.SellerName == nil {
			break
		}

		return e.complexity.Product.SellerName(childComplexity), true

	case "Product.slug":
		if e.complexity.Product.Slug == nil {
			break
		}

		return e.complexity.Product.Slug(childComplexity), true

	case "Product.status":
		if e.complexity.Product.Status == nil {
			break
		}

		return e.complexity.Product.Status(childComplexity), true

	case "Product.subcategoryID":
		if e.complexity.Product.SubcategoryID == nil {
			break
		}

		return e.complexity.Product.SubcategoryID(childComplexity), true

	case "Product.subcategoryName":
		if e.complexity.Product.SubcategoryName == nil {
			break
		}

		return e.complexity.Product.SubcategoryName(childComplexity), true

	case "Product.updatedAt":
		if e.complexity.Product.UpdatedAt == nil {
			break
		}

		return e.complexity.Product.UpdatedAt(childComplexity), true

	case "Product.variants":
		if e.complexity.Product.Variants == nil {
			break
		}

		return e.complexity.Product.Variants(childComplexity), true

	case "ProductByCategory.CategoryName":
		if e.complexity.ProductByCategory.CategoryName == nil {
			break
		}

		return e.complexity.ProductByCategory.CategoryName(childComplexity), true

	case "ProductByCategory.Products":
		if e.complexity.ProductByCategory.Products == nil {
			break
		}

		return e.complexity.ProductByCategory.Products(childComplexity), true

	case "ProductByCategory.TotalProducts":
		if e.complexity.ProductByCategory.TotalProducts == nil {
			break
		}

		return e.complexity.ProductByCategory.TotalProducts(childComplexity), true

	case "ProductCart.categoryID":
		if e.complexity.ProductCart.CategoryID == nil {
			break
		}

		return e.complexity.ProductCart.CategoryID(childComplexity), true

	case "ProductCart.categoryName":
		if e.complexity.ProductCart.CategoryName == nil {
			break
		}

		return e.complexity.ProductCart.CategoryName(childComplexity), true

	case "ProductCart.createdAt":
		if e.complexity.ProductCart.CreatedAt == nil {
			break
		}

		return e.complexity.ProductCart.CreatedAt(childComplexity), true

	case "ProductCart.description":
		if e.complexity.ProductCart.Description == nil {
			break
		}

		return e.complexity.ProductCart.Description(childComplexity), true

	case "ProductCart.id":
		if e.complexity.ProductCart.ID == nil {
			break
		}

		return e.complexity.ProductCart.ID(childComplexity), true

	case "ProductCart.imageUrl":
		if e.complexity.ProductCart.ImageURL == nil {
			break
		}

		return e.complexity.ProductCart.ImageURL(childComplexity), true

	case "ProductCart.name":
		if e.complexity.ProductCart.Name == nil {
			break
		}

		return e.complexity.ProductCart.Name(childComplexity), true

	case "ProductCart.sellerId":
		if e.complexity.ProductCart.SellerID == nil {
			break
		}

		return e.complexity.ProductCart.SellerID(childComplexity), true

	case "ProductCart.sellerName":
		if e.complexity.ProductCart.SellerName == nil {
			break
		}

		return e.complexity.ProductCart.SellerName(childComplexity), true

	case "ProductCart.slug":
		if e.complexity.ProductCart.Slug == nil {
			break
		}

		return e.complexity.ProductCart.Slug(childComplexity), true

	case "ProductCart.status":
		if e.complexity.ProductCart.Status == nil {
			break
		}

		return e.complexity.ProductCart.Status(childComplexity), true

	case "ProductCart.subcategoryID":
		if e.complexity.ProductCart.SubcategoryID == nil {
			break
		}

		return e.complexity.ProductCart.SubcategoryID(childComplexity), true

	case "ProductCart.subcategoryName":
		if e.complexity.ProductCart.SubcategoryName == nil {
			break
		}

		return e.complexity.ProductCart.SubcategoryName(childComplexity), true

	case "ProductCart.updatedAt":
		if e.complexity.ProductCart.UpdatedAt == nil {
			break
		}

		return e.complexity.ProductCart.UpdatedAt(childComplexity), true

	case "ProductCart.variant":
		if e.complexity.ProductCart.Variant == nil {
			break
		}

		return e.complexity.ProductCart.Variant(childComplexity), true

	case "ProductConnection.edges":
		if e.complexity.ProductConnection.Edges == nil {
			break
		}

		return e.complexity.ProductConnection.Edges(childComplexity), true

	case "ProductConnection.pageInfo":
		if e.complexity.ProductConnection.PageInfo == nil {
			break
		}

		return e.complexity.ProductConnection.PageInfo(childComplexity), true

	case "ProductConnection.totalCount":
		if e.complexity.ProductConnection.TotalCount == nil {
			break
		}

		return e.complexity.ProductConnection.TotalCount(childComplexity), true

	case "ProductEdge.cursor":
		if e.complexity.ProductEdge.Cursor == nil {
			break
		}

		return e.complexity.ProductEdge.Cursor(childComplexity), true

	case "ProductEdge.node":
		if e.complexity.ProductEdge.Node == nil {
			break
		}

		return e.complexity.ProductEdge.Node(childComplexity), true

	case "ProductPage.hasNext":
		if e.complexity.ProductPage.HasNext == nil {
			break
		}

		return e.complexity.ProductPage.HasNext(childComplexity), true

	case "ProductPage.items":
		if e.complexity.ProductPage.Items == nil {
			break
		}

		return e.complexity.ProductPage.Items(childComplexity), true

	case "ProductPage.limit":
		if e.complexity.ProductPage.Limit == nil {
			break
		}

		return e.complexity.ProductPage.Limit(childComplexity), true

	case "ProductPage.page":
		if e.complexity.ProductPage.Page == nil {
			break
		}

		return e.complexity.ProductPage.Page(childComplexity), true

	case "ProductPage.totalCount":
		if e.complexity.ProductPage.TotalCount == nil {
			break
		}

		return e.complexity.ProductPage.TotalCount(childComplexity), true

	case "ProductPage.totalPages":
		if e.complexity.ProductPage.TotalPages == nil {
			break
		}

		return e.complexity.ProductPage.TotalPages(childComplexity), true

	case "Query.category":
		if e.complexity.Query.Category == nil {
			break
		}

		args, err := ec.field_Query_category_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Category(childComplexity, args["filter"].(*string), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.myCart":
		if e.complexity.Query.MyCart == nil {
			break
		}

		args, err := ec.field_Query_myCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.MyCart(childComplexity, args["filter"].(*model.CartFilterInput), args["sort"].(*model.CartSortInput), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.orderDetail":
		if e.complexity.Query.OrderDetail == nil {
			break
		}

		args, err := ec.field_Query_orderDetail_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.OrderDetail(childComplexity, args["orderId"].(string)), true

	case "Query.orderList":
		if e.complexity.Query.OrderList == nil {
			break
		}

		args, err := ec.field_Query_orderList_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.OrderList(childComplexity, args["filter"].(*model.OrderFilterInput), args["sort"].(*model.OrderSortInput), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.packageRecomamendation":
		if e.complexity.Query.PackageRecomamendation == nil {
			break
		}

		args, err := ec.field_Query_packageRecomamendation_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.PackageRecomamendation(childComplexity, args["filter"].(*model.PackageFilterInput), args["sort"].(*model.PackageSortInput), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.productDetail":
		if e.complexity.Query.ProductDetail == nil {
			break
		}

		args, err := ec.field_Query_productDetail_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ProductDetail(childComplexity, args["productId"].(string)), true

	case "Query.productList":
		if e.complexity.Query.ProductList == nil {
			break
		}

		args, err := ec.field_Query_productList_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ProductList(childComplexity, args["filter"].(*model.ProductFilterInput), args["sort"].(*model.ProductSortInput), args["page"].(*int32), args["limit"].(*int32)), true

	case "Query.productsHome":
		if e.complexity.Query.ProductsHome == nil {
			break
		}

		args, err := ec.field_Query_productsHome_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ProductsHome(childComplexity, args["filter"].(*model.ProductFilterInput), args["sort"].(*model.ProductSortInput), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.subcategory":
		if e.complexity.Query.Subcategory == nil {
			break
		}

		args, err := ec.field_Query_subcategory_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Subcategory(childComplexity, args["filter"].(*string), args["categoryID"].(string), args["limit"].(*int32), args["page"].(*int32)), true

	case "Response.message":
		if e.complexity.Response.Message == nil {
			break
		}

		return e.complexity.Response.Message(childComplexity), true

	case "Response.success":
		if e.complexity.Response.Success == nil {
			break
		}

		return e.complexity.Response.Success(childComplexity), true

	case "Subcategory.categoryID":
		if e.complexity.Subcategory.CategoryID == nil {
			break
		}

		return e.complexity.Subcategory.CategoryID(childComplexity), true

	case "Subcategory.id":
		if e.complexity.Subcategory.ID == nil {
			break
		}

		return e.complexity.Subcategory.ID(childComplexity), true

	case "Subcategory.name":
		if e.complexity.Subcategory.Name == nil {
			break
		}

		return e.complexity.Subcategory.Name(childComplexity), true

	case "User.email":
		if e.complexity.User.Email == nil {
			break
		}

		return e.complexity.User.Email(childComplexity), true

	case "User.id":
		if e.complexity.User.ID == nil {
			break
		}

		return e.complexity.User.ID(childComplexity), true

	case "User.role":
		if e.complexity.User.Role == nil {
			break
		}

		return e.complexity.User.Role(childComplexity), true

	case "Variant.categoryID":
		if e.complexity.Variant.CategoryID == nil {
			break
		}

		return e.complexity.Variant.CategoryID(childComplexity), true

	case "Variant.createdAt":
		if e.complexity.Variant.CreatedAt == nil {
			break
		}

		return e.complexity.Variant.CreatedAt(childComplexity), true

	case "Variant.description":
		if e.complexity.Variant.Description == nil {
			break
		}

		return e.complexity.Variant.Description(childComplexity), true

	case "Variant.id":
		if e.complexity.Variant.ID == nil {
			break
		}

		return e.complexity.Variant.ID(childComplexity), true

	case "Variant.imageUrl":
		if e.complexity.Variant.ImageURL == nil {
			break
		}

		return e.complexity.Variant.ImageURL(childComplexity), true

	case "Variant.name":
		if e.complexity.Variant.Name == nil {
			break
		}

		return e.complexity.Variant.Name(childComplexity), true

	case "Variant.price":
		if e.complexity.Variant.Price == nil {
			break
		}

		return e.complexity.Variant.Price(childComplexity), true

	case "Variant.productId":
		if e.complexity.Variant.ProductID == nil {
			break
		}

		return e.complexity.Variant.ProductID(childComplexity), true

	case "Variant.quantityType":
		if e.complexity.Variant.QuantityType == nil {
			break
		}

		return e.complexity.Variant.QuantityType(childComplexity), true

	case "Variant.sellerId":
		if e.complexity.Variant.SellerID == nil {
			break
		}

		return e.complexity.Variant.SellerID(childComplexity), true

	case "Variant.stock":
		if e.complexity.Variant.Stock == nil {
			break
		}

		return e.complexity.Variant.Stock(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputAddToCartInput,
		ec.unmarshalInputCartFilterInput,
		ec.unmarshalInputCartSortInput,
		ec.unmarshalInputLoginInput,
		ec.unmarshalInputNewProduct,
		ec.unmarshalInputNewVariant,
		ec.unmarshalInputOrderFilterInput,
		ec.unmarshalInputOrderSortInput,
		ec.unmarshalInputPackageFilterInput,
		ec.unmarshalInputPackageSortInput,
		ec.unmarshalInputProductFilterInput,
		ec.unmarshalInputProductSortInput,
		ec.unmarshalInputRegisterInput,
		ec.unmarshalInputUpdateCartInput,
		ec.unmarshalInputUpdateOrderStatusInput,
		ec.unmarshalInputUpdateProduct,
		ec.unmarshalInputUpdateVariant,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

//go:embed "schema/cart.graphqls" "schema/category.graphqls" "schema/common.graphqls" "schema/order.graphqls" "schema/package.graphqls" "schema/pagination.graphqls" "schema/product.graphqls" "schema/schema.graphqls" "schema/user.graphqls" "schema/variant.graphqls"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "schema/cart.graphqls", Input: sourceData("schema/cart.graphqls"), BuiltIn: false},
	{Name: "schema/category.graphqls", Input: sourceData("schema/category.graphqls"), BuiltIn: false},
	{Name: "schema/common.graphqls", Input: sourceData("schema/common.graphqls"), BuiltIn: false},
	{Name: "schema/order.graphqls", Input: sourceData("schema/order.graphqls"), BuiltIn: false},
	{Name: "schema/package.graphqls", Input: sourceData("schema/package.graphqls"), BuiltIn: false},
	{Name: "schema/pagination.graphqls", Input: sourceData("schema/pagination.graphqls"), BuiltIn: false},
	{Name: "schema/product.graphqls", Input: sourceData("schema/product.graphqls"), BuiltIn: false},
	{Name: "schema/schema.graphqls", Input: sourceData("schema/schema.graphqls"), BuiltIn: false},
	{Name: "schema/user.graphqls", Input: sourceData("schema/user.graphqls"), BuiltIn: false},
	{Name: "schema/variant.graphqls", Input: sourceData("schema/variant.graphqls"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
