// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"context"
	"embed"
	"errors"
	"fmt"
	"sync/atomic"
	"warimas-be/internal/graph/model"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type DirectiveRoot struct {
	Auth func(ctx context.Context, obj any, next graphql.Resolver, role *model.Role) (res any, err error)
}

type ComplexityRoot struct {
	AddToCartResponse struct {
		CartItem func(childComplexity int) int
		Message  func(childComplexity int) int
		Success  func(childComplexity int) int
	}

	Address struct {
		AddressLine1 func(childComplexity int) int
		AddressLine2 func(childComplexity int) int
		City         func(childComplexity int) int
		Country      func(childComplexity int) int
		ID           func(childComplexity int) int
		IsDefault    func(childComplexity int) int
		Name         func(childComplexity int) int
		Phone        func(childComplexity int) int
		PostalCode   func(childComplexity int) int
		Province     func(childComplexity int) int
	}

	AuthResponse struct {
		Token func(childComplexity int) int
		User  func(childComplexity int) int
	}

	CartItem struct {
		CreatedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		Product   func(childComplexity int) int
		Quantity  func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
		UserID    func(childComplexity int) int
	}

	Category struct {
		ID   func(childComplexity int) int
		Name func(childComplexity int) int
	}

	CheckoutSession struct {
		Address     func(childComplexity int) int
		CreatedAt   func(childComplexity int) int
		Discount    func(childComplexity int) int
		ExpiresAt   func(childComplexity int) int
		ID          func(childComplexity int) int
		Items       func(childComplexity int) int
		ShippingFee func(childComplexity int) int
		Status      func(childComplexity int) int
		Subtotal    func(childComplexity int) int
		Tax         func(childComplexity int) int
		TotalPrice  func(childComplexity int) int
	}

	CheckoutSessionItem struct {
		ID           func(childComplexity int) int
		ImageURL     func(childComplexity int) int
		Price        func(childComplexity int) int
		Quantity     func(childComplexity int) int
		QuantityType func(childComplexity int) int
		Subtotal     func(childComplexity int) int
		VariantID    func(childComplexity int) int
		VariantName  func(childComplexity int) int
	}

	ConfirmCheckoutSessionResponse struct {
		Message func(childComplexity int) int
		Session func(childComplexity int) int
		Success func(childComplexity int) int
	}

	CreateAddressResponse struct {
		Address func(childComplexity int) int
	}

	CreateOrderResponse struct {
		Message    func(childComplexity int) int
		Order      func(childComplexity int) int
		Payment    func(childComplexity int) int
		PaymentURL func(childComplexity int) int
		Success    func(childComplexity int) int
	}

	DeleteAddressResponse struct {
		Success func(childComplexity int) int
	}

	Mutation struct {
		AddCategory            func(childComplexity int, name string) int
		AddSubcategory         func(childComplexity int, categoryID string, name string) int
		AddToCart              func(childComplexity int, input model.AddToCartInput) int
		ConfirmCheckoutSession func(childComplexity int, input model.ConfirmCheckoutSessionInput) int
		CreateAddress          func(childComplexity int, input model.CreateAddressInput) int
		CreateOrderFromSession func(childComplexity int, input model.CreateOrderFromSessionInput) int
		CreateProduct          func(childComplexity int, input model.NewProduct) int
		CreateSessionCheckout  func(childComplexity int, input model.CreateSessionCheckoutInput) int
		CreateVariants         func(childComplexity int, input []*model.NewVariant) int
		DeleteAddress          func(childComplexity int, input model.DeleteAddressInput) int
		Login                  func(childComplexity int, input model.LoginInput) int
		Register               func(childComplexity int, input model.RegisterInput) int
		RemoveFromCart         func(childComplexity int, variantID string) int
		SetDefaultAddress      func(childComplexity int, addressID string) int
		UpdateAddress          func(childComplexity int, input model.UpdateAddressInput) int
		UpdateCart             func(childComplexity int, input model.UpdateCartInput) int
		UpdateOrderStatus      func(childComplexity int, input model.UpdateOrderStatusInput) int
		UpdateProduct          func(childComplexity int, input model.UpdateProduct) int
		UpdateSessionAddress   func(childComplexity int, input model.UpdateSessionAddressInput) int
		UpdateVariants         func(childComplexity int, input []*model.UpdateVariant) int
	}

	Order struct {
		CreatedAt  func(childComplexity int) int
		ID         func(childComplexity int) int
		Items      func(childComplexity int) int
		Status     func(childComplexity int) int
		TotalPrice func(childComplexity int) int
		UpdatedAt  func(childComplexity int) int
		User       func(childComplexity int) int
	}

	OrderItem struct {
		ID       func(childComplexity int) int
		Price    func(childComplexity int) int
		Product  func(childComplexity int) int
		Quantity func(childComplexity int) int
	}

	OrderListResponse struct {
		Items func(childComplexity int) int
		Limit func(childComplexity int) int
		Page  func(childComplexity int) int
		Total func(childComplexity int) int
	}

	Package struct {
		ID       func(childComplexity int) int
		ImageURL func(childComplexity int) int
		Items    func(childComplexity int) int
		Name     func(childComplexity int) int
		UserID   func(childComplexity int) int
	}

	PackageItem struct {
		CreatedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		ImageURL  func(childComplexity int) int
		Name      func(childComplexity int) int
		PackageID func(childComplexity int) int
		Price     func(childComplexity int) int
		Quantity  func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
		VariantID func(childComplexity int) int
	}

	PackageResponse struct {
		Data    func(childComplexity int) int
		Message func(childComplexity int) int
		Success func(childComplexity int) int
	}

	PageInfo struct {
		EndCursor       func(childComplexity int) int
		HasNextPage     func(childComplexity int) int
		HasPreviousPage func(childComplexity int) int
		StartCursor     func(childComplexity int) int
	}

	Payment struct {
		Provider func(childComplexity int) int
		Status   func(childComplexity int) int
		URL      func(childComplexity int) int
	}

	Product struct {
		CategoryID      func(childComplexity int) int
		CategoryName    func(childComplexity int) int
		CreatedAt       func(childComplexity int) int
		Description     func(childComplexity int) int
		ID              func(childComplexity int) int
		ImageURL        func(childComplexity int) int
		Name            func(childComplexity int) int
		SellerID        func(childComplexity int) int
		SellerName      func(childComplexity int) int
		Slug            func(childComplexity int) int
		Status          func(childComplexity int) int
		SubcategoryID   func(childComplexity int) int
		SubcategoryName func(childComplexity int) int
		UpdatedAt       func(childComplexity int) int
		Variants        func(childComplexity int) int
	}

	ProductByCategory struct {
		CategoryName  func(childComplexity int) int
		Products      func(childComplexity int) int
		TotalProducts func(childComplexity int) int
	}

	ProductCart struct {
		CategoryID      func(childComplexity int) int
		CategoryName    func(childComplexity int) int
		CreatedAt       func(childComplexity int) int
		Description     func(childComplexity int) int
		ID              func(childComplexity int) int
		ImageURL        func(childComplexity int) int
		Name            func(childComplexity int) int
		SellerID        func(childComplexity int) int
		SellerName      func(childComplexity int) int
		Slug            func(childComplexity int) int
		Status          func(childComplexity int) int
		SubcategoryID   func(childComplexity int) int
		SubcategoryName func(childComplexity int) int
		UpdatedAt       func(childComplexity int) int
		Variant         func(childComplexity int) int
	}

	ProductConnection struct {
		Edges      func(childComplexity int) int
		PageInfo   func(childComplexity int) int
		TotalCount func(childComplexity int) int
	}

	ProductEdge struct {
		Cursor func(childComplexity int) int
		Node   func(childComplexity int) int
	}

	ProductPage struct {
		HasNext    func(childComplexity int) int
		Items      func(childComplexity int) int
		Limit      func(childComplexity int) int
		Page       func(childComplexity int) int
		TotalCount func(childComplexity int) int
		TotalPages func(childComplexity int) int
	}

	Query struct {
		Address                func(childComplexity int, addressID string) int
		Addresses              func(childComplexity int) int
		Category               func(childComplexity int, filter *string, limit *int32, page *int32) int
		CheckoutSession        func(childComplexity int, id string) int
		MyCart                 func(childComplexity int, filter *model.CartFilterInput, sort *model.CartSortInput, limit *int32, page *int32) int
		OrderDetail            func(childComplexity int, orderID string) int
		OrderList              func(childComplexity int, filter *model.OrderFilterInput, sort *model.OrderSortInput, limit *int32, page *int32) int
		PackageRecomamendation func(childComplexity int, filter *model.PackageFilterInput, sort *model.PackageSortInput, limit *int32, page *int32) int
		ProductDetail          func(childComplexity int, productID string) int
		ProductList            func(childComplexity int, filter *model.ProductFilterInput, sort *model.ProductSortInput, page *int32, limit *int32) int
		ProductsHome           func(childComplexity int, filter *model.ProductFilterInput, sort *model.ProductSortInput, page *int32, limit *int32) int
		Subcategory            func(childComplexity int, filter *string, categoryID string, limit *int32, page *int32) int
	}

	Response struct {
		Message func(childComplexity int) int
		Success func(childComplexity int) int
	}

	SessionCheckoutResponse struct {
		ExpiresAt func(childComplexity int) int
		SessionID func(childComplexity int) int
		Status    func(childComplexity int) int
	}

	Subcategory struct {
		CategoryID func(childComplexity int) int
		ID         func(childComplexity int) int
		Name       func(childComplexity int) int
	}

	UpdateAddressResponse struct {
		Address func(childComplexity int) int
	}

	UpdateSessionAddressResponse struct {
		Success func(childComplexity int) int
	}

	User struct {
		Email func(childComplexity int) int
		ID    func(childComplexity int) int
		Role  func(childComplexity int) int
	}

	Variant struct {
		CategoryID   func(childComplexity int) int
		CreatedAt    func(childComplexity int) int
		Description  func(childComplexity int) int
		ID           func(childComplexity int) int
		ImageURL     func(childComplexity int) int
		Name         func(childComplexity int) int
		Price        func(childComplexity int) int
		ProductID    func(childComplexity int) int
		QuantityType func(childComplexity int) int
		SellerID     func(childComplexity int) int
		Stock        func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "AddToCartResponse.cartItem":
		if e.complexity.AddToCartResponse.CartItem == nil {
			break
		}

		return e.complexity.AddToCartResponse.CartItem(childComplexity), true

	case "AddToCartResponse.message":
		if e.complexity.AddToCartResponse.Message == nil {
			break
		}

		return e.complexity.AddToCartResponse.Message(childComplexity), true

	case "AddToCartResponse.success":
		if e.complexity.AddToCartResponse.Success == nil {
			break
		}

		return e.complexity.AddToCartResponse.Success(childComplexity), true

	case "Address.addressLine1":
		if e.complexity.Address.AddressLine1 == nil {
			break
		}

		return e.complexity.Address.AddressLine1(childComplexity), true

	case "Address.addressLine2":
		if e.complexity.Address.AddressLine2 == nil {
			break
		}

		return e.complexity.Address.AddressLine2(childComplexity), true

	case "Address.city":
		if e.complexity.Address.City == nil {
			break
		}

		return e.complexity.Address.City(childComplexity), true

	case "Address.country":
		if e.complexity.Address.Country == nil {
			break
		}

		return e.complexity.Address.Country(childComplexity), true

	case "Address.id":
		if e.complexity.Address.ID == nil {
			break
		}

		return e.complexity.Address.ID(childComplexity), true

	case "Address.isDefault":
		if e.complexity.Address.IsDefault == nil {
			break
		}

		return e.complexity.Address.IsDefault(childComplexity), true

	case "Address.name":
		if e.complexity.Address.Name == nil {
			break
		}

		return e.complexity.Address.Name(childComplexity), true

	case "Address.phone":
		if e.complexity.Address.Phone == nil {
			break
		}

		return e.complexity.Address.Phone(childComplexity), true

	case "Address.postalCode":
		if e.complexity.Address.PostalCode == nil {
			break
		}

		return e.complexity.Address.PostalCode(childComplexity), true

	case "Address.province":
		if e.complexity.Address.Province == nil {
			break
		}

		return e.complexity.Address.Province(childComplexity), true

	case "AuthResponse.token":
		if e.complexity.AuthResponse.Token == nil {
			break
		}

		return e.complexity.AuthResponse.Token(childComplexity), true

	case "AuthResponse.user":
		if e.complexity.AuthResponse.User == nil {
			break
		}

		return e.complexity.AuthResponse.User(childComplexity), true

	case "CartItem.createdAt":
		if e.complexity.CartItem.CreatedAt == nil {
			break
		}

		return e.complexity.CartItem.CreatedAt(childComplexity), true

	case "CartItem.id":
		if e.complexity.CartItem.ID == nil {
			break
		}

		return e.complexity.CartItem.ID(childComplexity), true

	case "CartItem.product":
		if e.complexity.CartItem.Product == nil {
			break
		}

		return e.complexity.CartItem.Product(childComplexity), true

	case "CartItem.quantity":
		if e.complexity.CartItem.Quantity == nil {
			break
		}

		return e.complexity.CartItem.Quantity(childComplexity), true

	case "CartItem.updatedAt":
		if e.complexity.CartItem.UpdatedAt == nil {
			break
		}

		return e.complexity.CartItem.UpdatedAt(childComplexity), true

	case "CartItem.userId":
		if e.complexity.CartItem.UserID == nil {
			break
		}

		return e.complexity.CartItem.UserID(childComplexity), true

	case "Category.id":
		if e.complexity.Category.ID == nil {
			break
		}

		return e.complexity.Category.ID(childComplexity), true

	case "Category.name":
		if e.complexity.Category.Name == nil {
			break
		}

		return e.complexity.Category.Name(childComplexity), true

	case "CheckoutSession.address":
		if e.complexity.CheckoutSession.Address == nil {
			break
		}

		return e.complexity.CheckoutSession.Address(childComplexity), true

	case "CheckoutSession.createdAt":
		if e.complexity.CheckoutSession.CreatedAt == nil {
			break
		}

		return e.complexity.CheckoutSession.CreatedAt(childComplexity), true

	case "CheckoutSession.discount":
		if e.complexity.CheckoutSession.Discount == nil {
			break
		}

		return e.complexity.CheckoutSession.Discount(childComplexity), true

	case "CheckoutSession.expiresAt":
		if e.complexity.CheckoutSession.ExpiresAt == nil {
			break
		}

		return e.complexity.CheckoutSession.ExpiresAt(childComplexity), true

	case "CheckoutSession.id":
		if e.complexity.CheckoutSession.ID == nil {
			break
		}

		return e.complexity.CheckoutSession.ID(childComplexity), true

	case "CheckoutSession.items":
		if e.complexity.CheckoutSession.Items == nil {
			break
		}

		return e.complexity.CheckoutSession.Items(childComplexity), true

	case "CheckoutSession.shippingFee":
		if e.complexity.CheckoutSession.ShippingFee == nil {
			break
		}

		return e.complexity.CheckoutSession.ShippingFee(childComplexity), true

	case "CheckoutSession.status":
		if e.complexity.CheckoutSession.Status == nil {
			break
		}

		return e.complexity.CheckoutSession.Status(childComplexity), true

	case "CheckoutSession.subtotal":
		if e.complexity.CheckoutSession.Subtotal == nil {
			break
		}

		return e.complexity.CheckoutSession.Subtotal(childComplexity), true

	case "CheckoutSession.tax":
		if e.complexity.CheckoutSession.Tax == nil {
			break
		}

		return e.complexity.CheckoutSession.Tax(childComplexity), true

	case "CheckoutSession.totalPrice":
		if e.complexity.CheckoutSession.TotalPrice == nil {
			break
		}

		return e.complexity.CheckoutSession.TotalPrice(childComplexity), true

	case "CheckoutSessionItem.id":
		if e.complexity.CheckoutSessionItem.ID == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.ID(childComplexity), true

	case "CheckoutSessionItem.imageUrl":
		if e.complexity.CheckoutSessionItem.ImageURL == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.ImageURL(childComplexity), true

	case "CheckoutSessionItem.price":
		if e.complexity.CheckoutSessionItem.Price == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.Price(childComplexity), true

	case "CheckoutSessionItem.quantity":
		if e.complexity.CheckoutSessionItem.Quantity == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.Quantity(childComplexity), true

	case "CheckoutSessionItem.quantityType":
		if e.complexity.CheckoutSessionItem.QuantityType == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.QuantityType(childComplexity), true

	case "CheckoutSessionItem.subtotal":
		if e.complexity.CheckoutSessionItem.Subtotal == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.Subtotal(childComplexity), true

	case "CheckoutSessionItem.variantId":
		if e.complexity.CheckoutSessionItem.VariantID == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.VariantID(childComplexity), true

	case "CheckoutSessionItem.variantName":
		if e.complexity.CheckoutSessionItem.VariantName == nil {
			break
		}

		return e.complexity.CheckoutSessionItem.VariantName(childComplexity), true

	case "ConfirmCheckoutSessionResponse.message":
		if e.complexity.ConfirmCheckoutSessionResponse.Message == nil {
			break
		}

		return e.complexity.ConfirmCheckoutSessionResponse.Message(childComplexity), true

	case "ConfirmCheckoutSessionResponse.session":
		if e.complexity.ConfirmCheckoutSessionResponse.Session == nil {
			break
		}

		return e.complexity.ConfirmCheckoutSessionResponse.Session(childComplexity), true

	case "ConfirmCheckoutSessionResponse.success":
		if e.complexity.ConfirmCheckoutSessionResponse.Success == nil {
			break
		}

		return e.complexity.ConfirmCheckoutSessionResponse.Success(childComplexity), true

	case "CreateAddressResponse.address":
		if e.complexity.CreateAddressResponse.Address == nil {
			break
		}

		return e.complexity.CreateAddressResponse.Address(childComplexity), true

	case "CreateOrderResponse.message":
		if e.complexity.CreateOrderResponse.Message == nil {
			break
		}

		return e.complexity.CreateOrderResponse.Message(childComplexity), true

	case "CreateOrderResponse.order":
		if e.complexity.CreateOrderResponse.Order == nil {
			break
		}

		return e.complexity.CreateOrderResponse.Order(childComplexity), true

	case "CreateOrderResponse.payment":
		if e.complexity.CreateOrderResponse.Payment == nil {
			break
		}

		return e.complexity.CreateOrderResponse.Payment(childComplexity), true

	case "CreateOrderResponse.paymentURL":
		if e.complexity.CreateOrderResponse.PaymentURL == nil {
			break
		}

		return e.complexity.CreateOrderResponse.PaymentURL(childComplexity), true

	case "CreateOrderResponse.success":
		if e.complexity.CreateOrderResponse.Success == nil {
			break
		}

		return e.complexity.CreateOrderResponse.Success(childComplexity), true

	case "DeleteAddressResponse.success":
		if e.complexity.DeleteAddressResponse.Success == nil {
			break
		}

		return e.complexity.DeleteAddressResponse.Success(childComplexity), true

	case "Mutation.addCategory":
		if e.complexity.Mutation.AddCategory == nil {
			break
		}

		args, err := ec.field_Mutation_addCategory_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.AddCategory(childComplexity, args["name"].(string)), true

	case "Mutation.addSubcategory":
		if e.complexity.Mutation.AddSubcategory == nil {
			break
		}

		args, err := ec.field_Mutation_addSubcategory_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.AddSubcategory(childComplexity, args["categoryID"].(string), args["name"].(string)), true

	case "Mutation.addToCart":
		if e.complexity.Mutation.AddToCart == nil {
			break
		}

		args, err := ec.field_Mutation_addToCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.AddToCart(childComplexity, args["input"].(model.AddToCartInput)), true

	case "Mutation.confirmCheckoutSession":
		if e.complexity.Mutation.ConfirmCheckoutSession == nil {
			break
		}

		args, err := ec.field_Mutation_confirmCheckoutSession_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.ConfirmCheckoutSession(childComplexity, args["input"].(model.ConfirmCheckoutSessionInput)), true

	case "Mutation.createAddress":
		if e.complexity.Mutation.CreateAddress == nil {
			break
		}

		args, err := ec.field_Mutation_createAddress_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateAddress(childComplexity, args["input"].(model.CreateAddressInput)), true

	case "Mutation.createOrderFromSession":
		if e.complexity.Mutation.CreateOrderFromSession == nil {
			break
		}

		args, err := ec.field_Mutation_createOrderFromSession_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateOrderFromSession(childComplexity, args["input"].(model.CreateOrderFromSessionInput)), true

	case "Mutation.createProduct":
		if e.complexity.Mutation.CreateProduct == nil {
			break
		}

		args, err := ec.field_Mutation_createProduct_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateProduct(childComplexity, args["input"].(model.NewProduct)), true

	case "Mutation.createSessionCheckout":
		if e.complexity.Mutation.CreateSessionCheckout == nil {
			break
		}

		args, err := ec.field_Mutation_createSessionCheckout_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateSessionCheckout(childComplexity, args["input"].(model.CreateSessionCheckoutInput)), true

	case "Mutation.createVariants":
		if e.complexity.Mutation.CreateVariants == nil {
			break
		}

		args, err := ec.field_Mutation_createVariants_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateVariants(childComplexity, args["input"].([]*model.NewVariant)), true

	case "Mutation.deleteAddress":
		if e.complexity.Mutation.DeleteAddress == nil {
			break
		}

		args, err := ec.field_Mutation_deleteAddress_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteAddress(childComplexity, args["input"].(model.DeleteAddressInput)), true

	case "Mutation.login":
		if e.complexity.Mutation.Login == nil {
			break
		}

		args, err := ec.field_Mutation_login_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.Login(childComplexity, args["input"].(model.LoginInput)), true

	case "Mutation.register":
		if e.complexity.Mutation.Register == nil {
			break
		}

		args, err := ec.field_Mutation_register_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.Register(childComplexity, args["input"].(model.RegisterInput)), true

	case "Mutation.removeFromCart":
		if e.complexity.Mutation.RemoveFromCart == nil {
			break
		}

		args, err := ec.field_Mutation_removeFromCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.RemoveFromCart(childComplexity, args["variantId"].(string)), true

	case "Mutation.setDefaultAddress":
		if e.complexity.Mutation.SetDefaultAddress == nil {
			break
		}

		args, err := ec.field_Mutation_setDefaultAddress_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.SetDefaultAddress(childComplexity, args["addressId"].(string)), true

	case "Mutation.updateAddress":
		if e.complexity.Mutation.UpdateAddress == nil {
			break
		}

		args, err := ec.field_Mutation_updateAddress_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateAddress(childComplexity, args["input"].(model.UpdateAddressInput)), true

	case "Mutation.updateCart":
		if e.complexity.Mutation.UpdateCart == nil {
			break
		}

		args, err := ec.field_Mutation_updateCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateCart(childComplexity, args["input"].(model.UpdateCartInput)), true

	case "Mutation.updateOrderStatus":
		if e.complexity.Mutation.UpdateOrderStatus == nil {
			break
		}

		args, err := ec.field_Mutation_updateOrderStatus_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateOrderStatus(childComplexity, args["input"].(model.UpdateOrderStatusInput)), true

	case "Mutation.updateProduct":
		if e.complexity.Mutation.UpdateProduct == nil {
			break
		}

		args, err := ec.field_Mutation_updateProduct_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateProduct(childComplexity, args["input"].(model.UpdateProduct)), true

	case "Mutation.updateSessionAddress":
		if e.complexity.Mutation.UpdateSessionAddress == nil {
			break
		}

		args, err := ec.field_Mutation_updateSessionAddress_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateSessionAddress(childComplexity, args["input"].(model.UpdateSessionAddressInput)), true

	case "Mutation.updateVariants":
		if e.complexity.Mutation.UpdateVariants == nil {
			break
		}

		args, err := ec.field_Mutation_updateVariants_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateVariants(childComplexity, args["input"].([]*model.UpdateVariant)), true

	case "Order.createdAt":
		if e.complexity.Order.CreatedAt == nil {
			break
		}

		return e.complexity.Order.CreatedAt(childComplexity), true

	case "Order.id":
		if e.complexity.Order.ID == nil {
			break
		}

		return e.complexity.Order.ID(childComplexity), true

	case "Order.items":
		if e.complexity.Order.Items == nil {
			break
		}

		return e.complexity.Order.Items(childComplexity), true

	case "Order.status":
		if e.complexity.Order.Status == nil {
			break
		}

		return e.complexity.Order.Status(childComplexity), true

	case "Order.totalPrice":
		if e.complexity.Order.TotalPrice == nil {
			break
		}

		return e.complexity.Order.TotalPrice(childComplexity), true

	case "Order.updatedAt":
		if e.complexity.Order.UpdatedAt == nil {
			break
		}

		return e.complexity.Order.UpdatedAt(childComplexity), true

	case "Order.user":
		if e.complexity.Order.User == nil {
			break
		}

		return e.complexity.Order.User(childComplexity), true

	case "OrderItem.id":
		if e.complexity.OrderItem.ID == nil {
			break
		}

		return e.complexity.OrderItem.ID(childComplexity), true

	case "OrderItem.price":
		if e.complexity.OrderItem.Price == nil {
			break
		}

		return e.complexity.OrderItem.Price(childComplexity), true

	case "OrderItem.product":
		if e.complexity.OrderItem.Product == nil {
			break
		}

		return e.complexity.OrderItem.Product(childComplexity), true

	case "OrderItem.quantity":
		if e.complexity.OrderItem.Quantity == nil {
			break
		}

		return e.complexity.OrderItem.Quantity(childComplexity), true

	case "OrderListResponse.items":
		if e.complexity.OrderListResponse.Items == nil {
			break
		}

		return e.complexity.OrderListResponse.Items(childComplexity), true

	case "OrderListResponse.limit":
		if e.complexity.OrderListResponse.Limit == nil {
			break
		}

		return e.complexity.OrderListResponse.Limit(childComplexity), true

	case "OrderListResponse.page":
		if e.complexity.OrderListResponse.Page == nil {
			break
		}

		return e.complexity.OrderListResponse.Page(childComplexity), true

	case "OrderListResponse.total":
		if e.complexity.OrderListResponse.Total == nil {
			break
		}

		return e.complexity.OrderListResponse.Total(childComplexity), true

	case "Package.id":
		if e.complexity.Package.ID == nil {
			break
		}

		return e.complexity.Package.ID(childComplexity), true

	case "Package.imageUrl":
		if e.complexity.Package.ImageURL == nil {
			break
		}

		return e.complexity.Package.ImageURL(childComplexity), true

	case "Package.items":
		if e.complexity.Package.Items == nil {
			break
		}

		return e.complexity.Package.Items(childComplexity), true

	case "Package.name":
		if e.complexity.Package.Name == nil {
			break
		}

		return e.complexity.Package.Name(childComplexity), true

	case "Package.userId":
		if e.complexity.Package.UserID == nil {
			break
		}

		return e.complexity.Package.UserID(childComplexity), true

	case "PackageItem.createdAt":
		if e.complexity.PackageItem.CreatedAt == nil {
			break
		}

		return e.complexity.PackageItem.CreatedAt(childComplexity), true

	case "PackageItem.id":
		if e.complexity.PackageItem.ID == nil {
			break
		}

		return e.complexity.PackageItem.ID(childComplexity), true

	case "PackageItem.imageUrl":
		if e.complexity.PackageItem.ImageURL == nil {
			break
		}

		return e.complexity.PackageItem.ImageURL(childComplexity), true

	case "PackageItem.name":
		if e.complexity.PackageItem.Name == nil {
			break
		}

		return e.complexity.PackageItem.Name(childComplexity), true

	case "PackageItem.packageId":
		if e.complexity.PackageItem.PackageID == nil {
			break
		}

		return e.complexity.PackageItem.PackageID(childComplexity), true

	case "PackageItem.price":
		if e.complexity.PackageItem.Price == nil {
			break
		}

		return e.complexity.PackageItem.Price(childComplexity), true

	case "PackageItem.quantity":
		if e.complexity.PackageItem.Quantity == nil {
			break
		}

		return e.complexity.PackageItem.Quantity(childComplexity), true

	case "PackageItem.updatedAt":
		if e.complexity.PackageItem.UpdatedAt == nil {
			break
		}

		return e.complexity.PackageItem.UpdatedAt(childComplexity), true

	case "PackageItem.variantId":
		if e.complexity.PackageItem.VariantID == nil {
			break
		}

		return e.complexity.PackageItem.VariantID(childComplexity), true

	case "PackageResponse.data":
		if e.complexity.PackageResponse.Data == nil {
			break
		}

		return e.complexity.PackageResponse.Data(childComplexity), true

	case "PackageResponse.message":
		if e.complexity.PackageResponse.Message == nil {
			break
		}

		return e.complexity.PackageResponse.Message(childComplexity), true

	case "PackageResponse.success":
		if e.complexity.PackageResponse.Success == nil {
			break
		}

		return e.complexity.PackageResponse.Success(childComplexity), true

	case "PageInfo.endCursor":
		if e.complexity.PageInfo.EndCursor == nil {
			break
		}

		return e.complexity.PageInfo.EndCursor(childComplexity), true

	case "PageInfo.hasNextPage":
		if e.complexity.PageInfo.HasNextPage == nil {
			break
		}

		return e.complexity.PageInfo.HasNextPage(childComplexity), true

	case "PageInfo.hasPreviousPage":
		if e.complexity.PageInfo.HasPreviousPage == nil {
			break
		}

		return e.complexity.PageInfo.HasPreviousPage(childComplexity), true

	case "PageInfo.startCursor":
		if e.complexity.PageInfo.StartCursor == nil {
			break
		}

		return e.complexity.PageInfo.StartCursor(childComplexity), true

	case "Payment.provider":
		if e.complexity.Payment.Provider == nil {
			break
		}

		return e.complexity.Payment.Provider(childComplexity), true

	case "Payment.status":
		if e.complexity.Payment.Status == nil {
			break
		}

		return e.complexity.Payment.Status(childComplexity), true

	case "Payment.url":
		if e.complexity.Payment.URL == nil {
			break
		}

		return e.complexity.Payment.URL(childComplexity), true

	case "Product.categoryID":
		if e.complexity.Product.CategoryID == nil {
			break
		}

		return e.complexity.Product.CategoryID(childComplexity), true

	case "Product.categoryName":
		if e.complexity.Product.CategoryName == nil {
			break
		}

		return e.complexity.Product.CategoryName(childComplexity), true

	case "Product.createdAt":
		if e.complexity.Product.CreatedAt == nil {
			break
		}

		return e.complexity.Product.CreatedAt(childComplexity), true

	case "Product.description":
		if e.complexity.Product.Description == nil {
			break
		}

		return e.complexity.Product.Description(childComplexity), true

	case "Product.id":
		if e.complexity.Product.ID == nil {
			break
		}

		return e.complexity.Product.ID(childComplexity), true

	case "Product.imageUrl":
		if e.complexity.Product.ImageURL == nil {
			break
		}

		return e.complexity.Product.ImageURL(childComplexity), true

	case "Product.name":
		if e.complexity.Product.Name == nil {
			break
		}

		return e.complexity.Product.Name(childComplexity), true

	case "Product.sellerId":
		if e.complexity.Product.SellerID == nil {
			break
		}

		return e.complexity.Product.SellerID(childComplexity), true

	case "Product.sellerName":
		if e.complexity.Product.SellerName == nil {
			break
		}

		return e.complexity.Product.SellerName(childComplexity), true

	case "Product.slug":
		if e.complexity.Product.Slug == nil {
			break
		}

		return e.complexity.Product.Slug(childComplexity), true

	case "Product.status":
		if e.complexity.Product.Status == nil {
			break
		}

		return e.complexity.Product.Status(childComplexity), true

	case "Product.subcategoryID":
		if e.complexity.Product.SubcategoryID == nil {
			break
		}

		return e.complexity.Product.SubcategoryID(childComplexity), true

	case "Product.subcategoryName":
		if e.complexity.Product.SubcategoryName == nil {
			break
		}

		return e.complexity.Product.SubcategoryName(childComplexity), true

	case "Product.updatedAt":
		if e.complexity.Product.UpdatedAt == nil {
			break
		}

		return e.complexity.Product.UpdatedAt(childComplexity), true

	case "Product.variants":
		if e.complexity.Product.Variants == nil {
			break
		}

		return e.complexity.Product.Variants(childComplexity), true

	case "ProductByCategory.CategoryName":
		if e.complexity.ProductByCategory.CategoryName == nil {
			break
		}

		return e.complexity.ProductByCategory.CategoryName(childComplexity), true

	case "ProductByCategory.Products":
		if e.complexity.ProductByCategory.Products == nil {
			break
		}

		return e.complexity.ProductByCategory.Products(childComplexity), true

	case "ProductByCategory.TotalProducts":
		if e.complexity.ProductByCategory.TotalProducts == nil {
			break
		}

		return e.complexity.ProductByCategory.TotalProducts(childComplexity), true

	case "ProductCart.categoryID":
		if e.complexity.ProductCart.CategoryID == nil {
			break
		}

		return e.complexity.ProductCart.CategoryID(childComplexity), true

	case "ProductCart.categoryName":
		if e.complexity.ProductCart.CategoryName == nil {
			break
		}

		return e.complexity.ProductCart.CategoryName(childComplexity), true

	case "ProductCart.createdAt":
		if e.complexity.ProductCart.CreatedAt == nil {
			break
		}

		return e.complexity.ProductCart.CreatedAt(childComplexity), true

	case "ProductCart.description":
		if e.complexity.ProductCart.Description == nil {
			break
		}

		return e.complexity.ProductCart.Description(childComplexity), true

	case "ProductCart.id":
		if e.complexity.ProductCart.ID == nil {
			break
		}

		return e.complexity.ProductCart.ID(childComplexity), true

	case "ProductCart.imageUrl":
		if e.complexity.ProductCart.ImageURL == nil {
			break
		}

		return e.complexity.ProductCart.ImageURL(childComplexity), true

	case "ProductCart.name":
		if e.complexity.ProductCart.Name == nil {
			break
		}

		return e.complexity.ProductCart.Name(childComplexity), true

	case "ProductCart.sellerId":
		if e.complexity.ProductCart.SellerID == nil {
			break
		}

		return e.complexity.ProductCart.SellerID(childComplexity), true

	case "ProductCart.sellerName":
		if e.complexity.ProductCart.SellerName == nil {
			break
		}

		return e.complexity.ProductCart.SellerName(childComplexity), true

	case "ProductCart.slug":
		if e.complexity.ProductCart.Slug == nil {
			break
		}

		return e.complexity.ProductCart.Slug(childComplexity), true

	case "ProductCart.status":
		if e.complexity.ProductCart.Status == nil {
			break
		}

		return e.complexity.ProductCart.Status(childComplexity), true

	case "ProductCart.subcategoryID":
		if e.complexity.ProductCart.SubcategoryID == nil {
			break
		}

		return e.complexity.ProductCart.SubcategoryID(childComplexity), true

	case "ProductCart.subcategoryName":
		if e.complexity.ProductCart.SubcategoryName == nil {
			break
		}

		return e.complexity.ProductCart.SubcategoryName(childComplexity), true

	case "ProductCart.updatedAt":
		if e.complexity.ProductCart.UpdatedAt == nil {
			break
		}

		return e.complexity.ProductCart.UpdatedAt(childComplexity), true

	case "ProductCart.variant":
		if e.complexity.ProductCart.Variant == nil {
			break
		}

		return e.complexity.ProductCart.Variant(childComplexity), true

	case "ProductConnection.edges":
		if e.complexity.ProductConnection.Edges == nil {
			break
		}

		return e.complexity.ProductConnection.Edges(childComplexity), true

	case "ProductConnection.pageInfo":
		if e.complexity.ProductConnection.PageInfo == nil {
			break
		}

		return e.complexity.ProductConnection.PageInfo(childComplexity), true

	case "ProductConnection.totalCount":
		if e.complexity.ProductConnection.TotalCount == nil {
			break
		}

		return e.complexity.ProductConnection.TotalCount(childComplexity), true

	case "ProductEdge.cursor":
		if e.complexity.ProductEdge.Cursor == nil {
			break
		}

		return e.complexity.ProductEdge.Cursor(childComplexity), true

	case "ProductEdge.node":
		if e.complexity.ProductEdge.Node == nil {
			break
		}

		return e.complexity.ProductEdge.Node(childComplexity), true

	case "ProductPage.hasNext":
		if e.complexity.ProductPage.HasNext == nil {
			break
		}

		return e.complexity.ProductPage.HasNext(childComplexity), true

	case "ProductPage.items":
		if e.complexity.ProductPage.Items == nil {
			break
		}

		return e.complexity.ProductPage.Items(childComplexity), true

	case "ProductPage.limit":
		if e.complexity.ProductPage.Limit == nil {
			break
		}

		return e.complexity.ProductPage.Limit(childComplexity), true

	case "ProductPage.page":
		if e.complexity.ProductPage.Page == nil {
			break
		}

		return e.complexity.ProductPage.Page(childComplexity), true

	case "ProductPage.totalCount":
		if e.complexity.ProductPage.TotalCount == nil {
			break
		}

		return e.complexity.ProductPage.TotalCount(childComplexity), true

	case "ProductPage.totalPages":
		if e.complexity.ProductPage.TotalPages == nil {
			break
		}

		return e.complexity.ProductPage.TotalPages(childComplexity), true

	case "Query.address":
		if e.complexity.Query.Address == nil {
			break
		}

		args, err := ec.field_Query_address_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Address(childComplexity, args["addressId"].(string)), true

	case "Query.addresses":
		if e.complexity.Query.Addresses == nil {
			break
		}

		return e.complexity.Query.Addresses(childComplexity), true

	case "Query.category":
		if e.complexity.Query.Category == nil {
			break
		}

		args, err := ec.field_Query_category_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Category(childComplexity, args["filter"].(*string), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.checkoutSession":
		if e.complexity.Query.CheckoutSession == nil {
			break
		}

		args, err := ec.field_Query_checkoutSession_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.CheckoutSession(childComplexity, args["id"].(string)), true

	case "Query.myCart":
		if e.complexity.Query.MyCart == nil {
			break
		}

		args, err := ec.field_Query_myCart_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.MyCart(childComplexity, args["filter"].(*model.CartFilterInput), args["sort"].(*model.CartSortInput), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.orderDetail":
		if e.complexity.Query.OrderDetail == nil {
			break
		}

		args, err := ec.field_Query_orderDetail_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.OrderDetail(childComplexity, args["orderId"].(string)), true

	case "Query.orderList":
		if e.complexity.Query.OrderList == nil {
			break
		}

		args, err := ec.field_Query_orderList_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.OrderList(childComplexity, args["filter"].(*model.OrderFilterInput), args["sort"].(*model.OrderSortInput), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.packageRecomamendation":
		if e.complexity.Query.PackageRecomamendation == nil {
			break
		}

		args, err := ec.field_Query_packageRecomamendation_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.PackageRecomamendation(childComplexity, args["filter"].(*model.PackageFilterInput), args["sort"].(*model.PackageSortInput), args["limit"].(*int32), args["page"].(*int32)), true

	case "Query.productDetail":
		if e.complexity.Query.ProductDetail == nil {
			break
		}

		args, err := ec.field_Query_productDetail_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ProductDetail(childComplexity, args["productId"].(string)), true

	case "Query.productList":
		if e.complexity.Query.ProductList == nil {
			break
		}

		args, err := ec.field_Query_productList_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ProductList(childComplexity, args["filter"].(*model.ProductFilterInput), args["sort"].(*model.ProductSortInput), args["page"].(*int32), args["limit"].(*int32)), true

	case "Query.productsHome":
		if e.complexity.Query.ProductsHome == nil {
			break
		}

		args, err := ec.field_Query_productsHome_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ProductsHome(childComplexity, args["filter"].(*model.ProductFilterInput), args["sort"].(*model.ProductSortInput), args["page"].(*int32), args["limit"].(*int32)), true

	case "Query.subcategory":
		if e.complexity.Query.Subcategory == nil {
			break
		}

		args, err := ec.field_Query_subcategory_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Subcategory(childComplexity, args["filter"].(*string), args["categoryID"].(string), args["limit"].(*int32), args["page"].(*int32)), true

	case "Response.message":
		if e.complexity.Response.Message == nil {
			break
		}

		return e.complexity.Response.Message(childComplexity), true

	case "Response.success":
		if e.complexity.Response.Success == nil {
			break
		}

		return e.complexity.Response.Success(childComplexity), true

	case "SessionCheckoutResponse.expiresAt":
		if e.complexity.SessionCheckoutResponse.ExpiresAt == nil {
			break
		}

		return e.complexity.SessionCheckoutResponse.ExpiresAt(childComplexity), true

	case "SessionCheckoutResponse.sessionId":
		if e.complexity.SessionCheckoutResponse.SessionID == nil {
			break
		}

		return e.complexity.SessionCheckoutResponse.SessionID(childComplexity), true

	case "SessionCheckoutResponse.status":
		if e.complexity.SessionCheckoutResponse.Status == nil {
			break
		}

		return e.complexity.SessionCheckoutResponse.Status(childComplexity), true

	case "Subcategory.categoryID":
		if e.complexity.Subcategory.CategoryID == nil {
			break
		}

		return e.complexity.Subcategory.CategoryID(childComplexity), true

	case "Subcategory.id":
		if e.complexity.Subcategory.ID == nil {
			break
		}

		return e.complexity.Subcategory.ID(childComplexity), true

	case "Subcategory.name":
		if e.complexity.Subcategory.Name == nil {
			break
		}

		return e.complexity.Subcategory.Name(childComplexity), true

	case "UpdateAddressResponse.address":
		if e.complexity.UpdateAddressResponse.Address == nil {
			break
		}

		return e.complexity.UpdateAddressResponse.Address(childComplexity), true

	case "UpdateSessionAddressResponse.success":
		if e.complexity.UpdateSessionAddressResponse.Success == nil {
			break
		}

		return e.complexity.UpdateSessionAddressResponse.Success(childComplexity), true

	case "User.email":
		if e.complexity.User.Email == nil {
			break
		}

		return e.complexity.User.Email(childComplexity), true

	case "User.id":
		if e.complexity.User.ID == nil {
			break
		}

		return e.complexity.User.ID(childComplexity), true

	case "User.role":
		if e.complexity.User.Role == nil {
			break
		}

		return e.complexity.User.Role(childComplexity), true

	case "Variant.categoryID":
		if e.complexity.Variant.CategoryID == nil {
			break
		}

		return e.complexity.Variant.CategoryID(childComplexity), true

	case "Variant.createdAt":
		if e.complexity.Variant.CreatedAt == nil {
			break
		}

		return e.complexity.Variant.CreatedAt(childComplexity), true

	case "Variant.description":
		if e.complexity.Variant.Description == nil {
			break
		}

		return e.complexity.Variant.Description(childComplexity), true

	case "Variant.id":
		if e.complexity.Variant.ID == nil {
			break
		}

		return e.complexity.Variant.ID(childComplexity), true

	case "Variant.imageUrl":
		if e.complexity.Variant.ImageURL == nil {
			break
		}

		return e.complexity.Variant.ImageURL(childComplexity), true

	case "Variant.name":
		if e.complexity.Variant.Name == nil {
			break
		}

		return e.complexity.Variant.Name(childComplexity), true

	case "Variant.price":
		if e.complexity.Variant.Price == nil {
			break
		}

		return e.complexity.Variant.Price(childComplexity), true

	case "Variant.productId":
		if e.complexity.Variant.ProductID == nil {
			break
		}

		return e.complexity.Variant.ProductID(childComplexity), true

	case "Variant.quantityType":
		if e.complexity.Variant.QuantityType == nil {
			break
		}

		return e.complexity.Variant.QuantityType(childComplexity), true

	case "Variant.sellerId":
		if e.complexity.Variant.SellerID == nil {
			break
		}

		return e.complexity.Variant.SellerID(childComplexity), true

	case "Variant.stock":
		if e.complexity.Variant.Stock == nil {
			break
		}

		return e.complexity.Variant.Stock(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputAddToCartInput,
		ec.unmarshalInputAddressInput,
		ec.unmarshalInputCartFilterInput,
		ec.unmarshalInputCartSortInput,
		ec.unmarshalInputConfirmCheckoutSessionInput,
		ec.unmarshalInputCreateAddressInput,
		ec.unmarshalInputCreateOrderFromSessionInput,
		ec.unmarshalInputCreateSessionCheckoutInput,
		ec.unmarshalInputDeleteAddressInput,
		ec.unmarshalInputLoginInput,
		ec.unmarshalInputNewProduct,
		ec.unmarshalInputNewVariant,
		ec.unmarshalInputOrderFilterInput,
		ec.unmarshalInputOrderSortInput,
		ec.unmarshalInputPackageFilterInput,
		ec.unmarshalInputPackageSortInput,
		ec.unmarshalInputProductFilterInput,
		ec.unmarshalInputProductSortInput,
		ec.unmarshalInputRegisterInput,
		ec.unmarshalInputSessionCheckoutItemInput,
		ec.unmarshalInputUpdateAddressInput,
		ec.unmarshalInputUpdateCartInput,
		ec.unmarshalInputUpdateOrderStatusInput,
		ec.unmarshalInputUpdateProduct,
		ec.unmarshalInputUpdateSessionAddressInput,
		ec.unmarshalInputUpdateVariant,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

//go:embed "schema/address.graphqls" "schema/cart.graphqls" "schema/category.graphqls" "schema/common.graphqls" "schema/order.graphqls" "schema/package.graphqls" "schema/pagination.graphqls" "schema/product.graphqls" "schema/schema.graphqls" "schema/user.graphqls" "schema/variant.graphqls"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "schema/address.graphqls", Input: sourceData("schema/address.graphqls"), BuiltIn: false},
	{Name: "schema/cart.graphqls", Input: sourceData("schema/cart.graphqls"), BuiltIn: false},
	{Name: "schema/category.graphqls", Input: sourceData("schema/category.graphqls"), BuiltIn: false},
	{Name: "schema/common.graphqls", Input: sourceData("schema/common.graphqls"), BuiltIn: false},
	{Name: "schema/order.graphqls", Input: sourceData("schema/order.graphqls"), BuiltIn: false},
	{Name: "schema/package.graphqls", Input: sourceData("schema/package.graphqls"), BuiltIn: false},
	{Name: "schema/pagination.graphqls", Input: sourceData("schema/pagination.graphqls"), BuiltIn: false},
	{Name: "schema/product.graphqls", Input: sourceData("schema/product.graphqls"), BuiltIn: false},
	{Name: "schema/schema.graphqls", Input: sourceData("schema/schema.graphqls"), BuiltIn: false},
	{Name: "schema/user.graphqls", Input: sourceData("schema/user.graphqls"), BuiltIn: false},
	{Name: "schema/variant.graphqls", Input: sourceData("schema/variant.graphqls"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
