package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"warimas-be/internal/graph/model"
	"warimas-be/internal/utils"
)

// CreateVariants is the resolver for the createVariants field.
func (r *mutationResolver) CreateVariants(ctx context.Context, input []*model.NewVariant) ([]*model.Variant, error) {
	_, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized: please login first")
	}

	v, err := r.ProductSvc.CreateVariants(ctx, input)
	if err != nil {
		return nil, err
	}

	return v, nil
}

// UpdateVariants is the resolver for the updateVariants field.
func (r *mutationResolver) UpdateVariants(ctx context.Context, input []*model.UpdateVariant) ([]*model.Variant, error) {
	_, ok := utils.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized: please login first")
	}

	v, err := r.ProductSvc.UpdateVariants(ctx, input)
	if err != nil {
		return nil, err
	}

	return v, nil
}
